#! /bin/tcsh -f


echo "***    *** ***    ***     ***    **   *******"
echo "**  * * **   **  **       ***    **      *"
echo "**   *  **     **    ***  ***    **      *"
echo "**      **     **         ***    **      *"
echo "**      **     **         *********   *******"
echo " "
echo "       An unique User Interface (UI) that will take RTL netlist and SDC constraints as input and  will generate synthesized netlist & pre-layout timing report as an output. It uses YOSYS open source tool for synthesis and OpenTimer to generate pre-layout timing reports."
echo " "
echo "                For any queries & bugs drop a mail to keshavkumarsd@gmail.com "
echo " "

#-------------------------TOOL Initialization-----------------------------------------#


if ($#argv != 1) then
	echo "Info: Please provide the CSV file"
	exit 1 
endif

if (! -f $argv[1] || $argv[1] == "-help" ) then
   if($argv[1] != "-help") then
   	echo "Error: Cannot find csv file $argv[1]. Exiting...."
	exit 1
   else
   	echo USAGE: ./my_tcl_utility \<csv file\>
	echo
	echo         where \<csv file\> consists of 2 columns, below keyword being in 1st column and  is case Sensitive.Please request VSD team for sample csv file

	echo
	echo         \<Design name\> is the name of top level module
	echo
	echo         \<output Directory\> is the name of output directory where you want to dump synthesis script,synthesized netlist and timing reports
	echo
	echo         \<Netlist Directory\> is the name of directory where all RTL netlist are present
	echo
	echo         \<Early Library Path\> is the file path of the early cell library to be used for STA
	echo
	echo         \<Late Library Path\> is the path of the late cell library to be used for Sta
	echo
	echo         \<Constarints file\> is csv file path of constraints to be used for STA
	echo
	echo
	exit 1
	endif
else
	tclsh my_tcl_utility.tcl $argv[1]
endif
